### ISSUE TITLE
Add acknowledgements to ERC20.sol

### ISSUE THREAD

**Issue by abcoathup** [maple-labs/erc20#3]
I suggest adding the acknowledgements section from the README to the comments of the ERC20.sol so they don't get lost if the Solidity is copy/pasted

https://github.com/maple-labs/erc-20#acknowledgements

**Comment by abcoathup** [comment]
Depending how inspired the contract was, you could add a reference to the actual contracts and what license they use.
OpenZeppelin uses MIT, the other two projects use AGPL

See the example in OpenZeppelin:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cec4f2ef57495d8b1742d62846da212515d99dd5/contracts/utils/Strings.sol#L15-L16

**Comment by lucas-manuel** [comment]
> I suggest adding the acknowledgements section from the README to the comments of the ERC20.sol so they don't get lost if the Solidity is copy/pasted
> 
> https://github.com/maple-labs/erc-20#acknowledgements

Added thanks!
